version: '3.9'
services:
  profile-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${PROFILE_DB_NAME}
      POSTGRES_PASSWORD: ${PROFILE_DB_PASSWORD}
      POSTGRES_USER: ${PROFILE_DB_USER}
      DB_HOST: ${PROFILE_DB_HOST}
      DB_PORT: ${PROFILE_DB_PORT}
      POSTGRES_URL: ${PROFILE_DB_URL}
    volumes:
      - ./db-schemas/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - profile-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
