"""constraints

Revision ID: f5497384170e
Revises: 6f6aa1df4b63
Create Date: 2023-05-19 20:16:20.778616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5497384170e'
down_revision = '6f6aa1df4b63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['id', 'user_id'], schema='content')
    op.create_unique_constraint(None, 'profile_movies', ['profile_id', 'movie_id'], schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_user_ctr', schema='content', type_='unique')
    op.drop_constraint(None, 'profile_movie_ctr', schema='content', type_='unique')
    # ### end Alembic commands ###
