"""03_user_favorite_movies_constraint

Revision ID: f7c6f91df732
Revises: f5497384170e
Create Date: 2023-05-16 21:25:02.383785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c6f91df732'
down_revision = 'f5497384170e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_favorite_movies', ['user_id', 'movie_id'], schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorite_movies', schema='content', type_='unique')
    # ### end Alembic commands ###
