name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          pip install mypy
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Test with pytest
        run: |
          pytest

      - name: Telegram Notify
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.job }} job in workflow ${{ github.workflow }} ${{ matrix.python-version }} of ${{ github.repository }} has ${{ job.status }}
